#NAME: Dhakshin Suriakannu
#EMAIL: bruindhakshin@g.ucla.edu
#ID: 605280083
CC = gcc

default:
	$(CC) -o lab1a -Wall -Wextra lab1a.c 
clean:
	rm -f lab1a lab1a-605280083.tar.gz
dist:
	tar -cvzf lab1a-605280083.tar.gz lab1a.c README Makefile